name: CI
on: [push, pull_request]
jobs:
  rufo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rufo
        run: bundle exec rake rufo:check
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rake rubocop
  test_ruby_2:
    runs-on: ubuntu-latest
    needs: [rufo, rubocop]
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Bundler
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rake test
  test_ruby_3:
    runs-on: ubuntu-latest
    needs: [rufo, rubocop]
    strategy:
      fail-fast: false
      matrix:
        # 3.0 has to be in quotes since otherwise it would be interpreted as the latest 3.X version https://github.com/actions/runner/issues/849
        ruby-version: ['3.0', 3.1, 3.2, 3.3, 3.4] 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle lock --update
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rake test
